# .gitlab-ci.yml

image: maven:latest

stages:
  - build
  - test
  - pmd
build:
  stage: build
  script:
    - echo "Aufbau der Dockerumgebung"
    - mvn compile
test:
  stage: test
  script:
    - touch surefire-reports.xml
    - mvn test
    - echo "maven test done"
  artifacts:
    paths:
      - surefire-reports.xml
    when: always
    access: all
    expire_in: "30 days"
    

pmd:
  stage: pmd
  script:
    - mvn pmd:check || true