# .gitlab-ci.yml

image: maven:latest

stages:
  - build
  - test
  - pmd
build:
  stage: build
  script:
    - echo "Aufbau der Dockerumgebung"
    - mvn compile
test:
  stage: test
  script:
    - mvn test
    - echo "maven test done"
    - touch surefire-reports.xml
  artifacts:
    when: always
    paths:
      - surefire-reports.xml
    expire_in: "30 days"

pmd:
  stage: pmd
  script:
    - mvn pmd:check
  allow_failure: true