# .gitlab-ci.yml

image: maven:latest

stages:
  - build
  - test
  - pmd
build:
  stage: build
  script:
    - echo "Aufbau der Dockerumgebung"
    - mvn compile
test:
  stage: test
  script:
    - touch surefire-reports.xml
    - mvn test > surefire-reports.xml
    - echo "maven test done"

pmd:
  stage: pmd
  script:
    - mvn pmd:check || true