image: maven:latest

stages:
  - build
  - test
  - checkstyle

.some_script:
  before_script:
    - echo "Erstellt Datei"
    - touch surefire-reports2.xml

.some_script2:
  before_script:
    - echo "Erstellt Datei"
    - touch checkstyle-result2.xml

build:
  stage: build
  script:
    - echo "Aufbau der Dockerumgebung"
    - mvn compile

test:
  stage: test
  extends: .some_script
  script:
    - mvn test
    - ls -l
    - sleep 5
    - cp ./target/surefire-reports.xml checkstyle-result2.xml
  artifacts:
    when: always
    paths:
      - surefire-reports2.xml
    expire_in: "30 days"

checkstyle:
  stage: checkstyle
  extends: .some_script2
  script:
    - mvn checkstyle:checkstyle
    - ls -l
    - sleep 5
    - cp ./target/checkstyle-result.xml checkstyle-result2.xml
  artifacts:
    paths:
      - checkstyle-result2.xml
    expire_in: "1 week"
  allow_failure: true