image: maven:latest

stages:
  - build
  - test
  - checkstyle

.some_script:
  before_script:
    - echo "Erstellt Datei"
    - touch surefire-reports

.some_script2:
  before_script:
    - echo "Erstellt Datei"
    - touch checkstyle-result.xml

build:
  stage: build
  script:
    - echo "Aufbau der Dockerumgebung"
    - mvn compile

test:
  stage: test
  extends: .some_script
  script:
    - mvn test
    - ls -l
  artifacts:
    when: always
    paths:
      - mv target/surefire-reports.xml surefire-reports.xml
    expire_in: "30 days"

checkstyle:
  stage: checkstyle
  extends: .some_script2
  script:
    - mvn checkstyle:checkstyle
    - ls -l
    - ls -l target
  artifacts:
    paths:
      - mv target/checkstyle-result.xml checkstyle-result.xml
    expire_in: "1 week"
  allow_failure: true