# .gitlab-ci.yml

image: maven:latest

stages:
  - build
  - test
  - checkstyle


.some_script:
  before_script:
    - echo "erstellt Datei"
    - touch surefire-reports.xml

.some_script2:
  before_script:
    - echo "erstellt Datei"
    - touch checkstyle-result.xml

build:
  stage: build
  script:
    - echo "Aufbau der Dockerumgebung"
    - mvn compile

test:
  stage: test
  extends: .some_script
  script:
    - mvn test
    - echo "maven test done"
  artifacts:
    when: always
    paths:
      - surefire-reports.xml
    expire_in: "30 days"

checkstyle:
  stage: checkstyle
  extends: .some_script2
  script:
    - mvn checkstyle:checkstyle
  artifacts:
    paths:
      - checkstyle-result.xml
    expire_in: "1 week"
  allow_failure: true

