spring:
  datasource:
    username: lf8
    password: password
    url: jdbc:h2:file:/data/demo
    driverClassName: org.h2.Driver
  h2:
    console.enabled: true
  jpa:
    spring.jpa.database-platform: org.hibernate.dialect.H2Dialect
    defer-datasource-initialization=true:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MariaDBDialect